# Generated by Django 3.1.4 on 2020-12-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0002_auto_20201222_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Programming', 'Programming'), ('Science', 'Science'), ('Electrical', 'Electrical')], default='Science', help_text='Enter your Subject', max_length=30),
        ),
    ]
