# Generated by Django 3.1.4 on 2020-12-28 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0002_auto_20201222_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('Engineering', (('SE', 'Software Engineering'), ('CE', 'Computer Engineering'), ('EE', 'Electrical Engineering'))), ('Commerce', (('BBA', 'Bachelor of Business Administration'), ('CA', 'Chartered Accountancy'))), ('Medical', (('NS', 'Neuroscience'), ('MBBS', 'Bachelor of Medicine, Bachelor of Surgery')))], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_app.courses'),
        ),
    ]
