# Generated by Django 3.1.4 on 2020-12-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0005_auto_20201229_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(null=True, upload_to='static/user_imgs/'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
