# Generated by Django 3.1.4 on 2020-12-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0006_auto_20201229_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
            ],
        ),
    ]
