# Generated by Django 3.1.4 on 2020-12-29 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0007_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_app.courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
