# Generated by Django 3.1.4 on 2020-12-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0008_auto_20201229_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ManyToManyField(null=True, to='custom_app.Courses'),
        ),
    ]
