# Generated by Django 3.1.4 on 2020-12-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0019_auto_20201230_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
