# Generated by Django 3.1.4 on 2020-12-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0020_auto_20201230_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
