# Generated by Django 3.1.4 on 2020-12-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0021_auto_20201230_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
