# Generated by Django 2.0.5 on 2020-12-17 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_model_cust_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_product_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer_model',
            name='cust_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='customer_product_model',
            name='purchased_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_model'),
        ),
    ]
