# Generated by Django 2.0.5 on 2020-12-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_number', models.TextField(default='03XX-XXXXXXX')),
            ],
        ),
    ]
